Fix wallet unlock
coingaming/lnd-client pull request #158
Opened 2022-11-14 15:32 UTC by prushin

2022-11-14 15:34 UTC, prushin commented on src/LndClient/RPC/Katip.hs
> +    Left err -> do
There is no specific error text, also use specific text is not relaible, so let's try to intercept any error and if it helps, okay, if not - function will return error.

2022-11-16 10:59 UTC, drownbes approved these changes

2022-11-16 11:44 UTC, tim2CF requested changes
Some fixes

2022-11-16 11:44 UTC, tim2CF commented on src/LndClient/RPC/Katip.hs
> +          x
This is implicit repeat of original RPC call. It's dangerous, some RPCs might be not suitable for safe retries. For example SendCoins. Let's leave it as it was, just returning result whatever is was. Retries are handled separately in other combinator.

2022-11-16 11:44 UTC, tim2CF commented on src/LndClient/RPC/Katip.hs
> +          pure $ Left err0
The same, unlock is just a side effect, let's have original result here.

2022-11-16 11:44 UTC, tim2CF commented on src/LndClient/RPC/Silent.hs
> +        Right () -> x
The same, do not retry here, leave it as it was.

2022-11-16 11:44 UTC, tim2CF commented on src/LndGrpc/Client.hs
> +    Right (Right (Right (Right (_, _, Right x)))) -> do
"do" is redundant

2022-11-16 14:02 UTC, tim2CF approved these changes
Good job!

2022-11-16 14:02 UTC, merged