B1 m2 1312
coingaming/lnd-client pull request #82
Opened 2021-05-04 08:55 UTC by tim2CF

2021-05-04 09:35 UTC, prushin approved these changes

2021-05-05 07:55 UTC, drownbes requested changes

2021-05-05 07:55 UTC, drownbes commented on src/LndClient/LndTest.hs
> +      Lnd.GetInfoResponse alicePubKey _ _ <-
is this still Alice or owner0 pubKey?

2021-05-05 07:59 UTC, drownbes approved these changes

2021-05-05 08:26 UTC, merged